[tool.pytest.ini_options]
# callecta ll tags with:
# cat test/tm-cases/*tags \
#  | sed 's/#.*//' \
#  | tr ' ' '\n' \
#  | sort \
#  | uniq \
#  | tr '-' '_' \
#  | awk '{print "    \"" $1 "\","}'

markers = [
    "blank",
    "code_color",
    "code_as_com",
    "code_friendly",
    "cuddle_lists",
    "dontcare",
    "emacs",
    "eol",
    "escape",
    "extra",
    "extras",
    "fenced_code_blocks",
    "footnotes",
    "fromphpmarkdown",
    "header_ids",
    "highlightjs_lang",
    "html_classes",
    "htmlentities",
    "indentation",
    "issue104",
    "issue113",
    "issue127",
    "issue135",
    "issue15",
    "issue16",
    "issue165",
    "issue18",
    "issue21",
    "issue213",
    "issue216",
    "issue24",
    "issue26",
    "issue27",
    "issue3",
    "issue30",
    "issue33",
    "issue36",
    "issue42",
    "issue52",
    "issue54",
    "issue57",
    "issue67",
    "issue7",
    "issue74",
    "issue76",
    "issue78",
    "issue84",
    "issue86",
    "issue87",
    "issue9",
    "issue90",
    "knownfailure",
    "link_patterns",
    "markdown_in_html",
    "metadata",
    "nofollow",
    "pi",
    "pygments",
    "pyshell",
    "questionable",
    "safe_mode",
    "smarty_pants",
    "smedberg",
    "strike",
    "tables",
    "tag_friendly",
    "task_list",
    "toc",
    "underline",
    "unicode",
    "wiki_tables",
    "xinclude",
    "xml",
]
